name: Build & Test

on:
  push:
    branches: [ "main", "rel-*" ]

env:
  NAME: Avikalp Gupta

jobs: # each job will run in its own VM

  build:

    runs-on: ubuntu-20.04 # each build can have its own OS

    timeout-minutes: 5

    steps:

      - name: Greet user
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

  test: # this job will run in parallel with the "build" job

    runs-on: ubuntu-22.04

    timeout-minutes: 10

    env:
      NAME: Planet # you can use different environment variables for each job

    steps:

      - name: Step inside test job
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"



