name: Build & Test

on:
  push:
    branches: [ "main", "rel-*" ]

env:
  NAME: Avikalp Gupta

jobs: # each job will run in its own VM

  build:

    runs-on: ubuntu-20.04 # each build can have its own OS

    timeout-minutes: 5

    steps:

      - name: Greet user
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

  gen-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.execute.outputs.matrix }}
    steps:
      - name: Get test combinations
        id: execute
        run: | # github.event.head_commit.message lets you control the strategy from commit message; Here: @@mobile
          echo Commit message: ${{ github.event.head_commit.message }}
          combs='{"browser": ["chrome", "firefox"], "device": ["desktop", "mobile"]}'
          if [[ "${{ github.event.head_commit.message }}" == *@@mobile* ]]; then
            # If commit message has @@mobile, ignore desktop and execute only for mobile
            matrix=$(echo $combs | sed -e 's/"desktop", //')
          else
            matrix=$combs
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        # $GITHUB_OUTPUT lets the next steps to access the value computed

      - name: Access output of prev step
        run: echo ${{ steps.execute.outputs.matrix }}

  test: # this job will run in parallel with the "build" job

    # fromJSON is a in-built function provided by Github Actions
    strategy: ${{ fromJSON(needs.gen-matrix.outputs.matrix) }}

    runs-on: ubuntu-22.04

    needs: [build, gen-matrix]

    timeout-minutes: 10

    env:
      NAME: Earth # you can use different environment variables for each job

    steps:

      - name: Demo of how to access current matrix context
        run: |
          echo "Browser:" ${{ matrix.browser }}
          echo "Device: ${{ matrix.device }}"

      - name: Step inside test job
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

      - name: Disabled step
        if: false
        run: echo "This step may be enabled when debugging"

      - name: Conditional step
        if: ${{ github.ref == 'refs/heads/main' }} # condition for only running this if HEAD is on main
        run: echo "Execute this step conditionally, only on main branch"



