name: Build & Test

on:
  push:
    branches: [ "main", "rel-*" ]

env:
  NAME: Avikalp Gupta

jobs: # each job will run in its own VM

  build:

    runs-on: ubuntu-20.04 # each build can have its own OS

    timeout-minutes: 5

    steps:

      - name: Greet user
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

  test: # this job will run in parallel with the "build" job

    strategy: # this runs 8 VMs, but only 2 in parallel at a time
      max-parallel: 2 # controls the max number of VMs running in parallel. Otherwise it will run all possible combinations in parallel
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        browser: [chrome, firefox]
        device: [desktop, mobile]
        include:
          - os: windows-latest
            browser: edge
            device: desktop
        exclude:
          - os: ubuntu-20.04
            browser: chrome
            device: mobile

    runs-on: ${{ matrix.os }}

    needs: build

    timeout-minutes: 10

    env:
      NAME: Planet # you can use different environment variables for each job

    steps:

      - name: Demo of how to access current matrix context
        run: |
          echo "Browser:" ${{ matrix.browser }}
          echo "Device: ${{ matrix.device }}"

      - name: Step inside test job
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"



