name: Build & Test

on:
  push:
    branches: [ "main", "rel-*" ]
  schedule:
    - cron: '45 11 * * *' # 11:45 AM GMT (5:15 PM IST) daily

env:
  NAME: Avikalp Gupta

jobs: # each job will run in its own VM

  build:

    runs-on: ubuntu-20.04 # each build can have its own OS

    timeout-minutes: 5

    steps:

      - name: Greet user
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

  gen-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.execute.outputs.matrix }}
    steps:
      - name: Get test combinations
        id: execute
        run: | # github.event.head_commit.message lets you control the strategy from commit message; Here: @@mobile
          echo Commit message: ${{ github.event.head_commit.message }}
          combs='{"browser": ["chrome", "firefox"], "device": ["desktop", "mobile"]}'
          if [[ "${{ github.event.head_commit.message }}" == *@@mobile* ]]; then
            # If commit message has @@mobile, ignore desktop and execute only for mobile
            matrix=$(echo $combs | sed -e 's/"desktop", //')
          else
            matrix=$combs
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        # $GITHUB_OUTPUT lets the next steps to access the value computed

      - name: Access output of prev step
        run: echo ${{ steps.execute.outputs.matrix }}

  test: # this job will run in parallel with the "build" job

    strategy:
      matrix: ${{ fromJSON(needs.gen-matrix.outputs.matrix) }} # fromJSON is a in-built function provided by Github Actions

    runs-on: ubuntu-22.04

    timeout-minutes: 5

    needs: [build, gen-matrix]

    env:
      NAME: Planet

    steps:

      - name: Demo of how to access current matrix context
        run: |
          echo "Browser: " ${{ matrix.browser }}
          echo "Device: ${{ matrix.device }}"

      - name: Step inside test job
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

      - name: Disabled step
        if: false
        run: echo "This step may be enabled when debugging"

      - name: Conditional step
        if: ${{ github.ref == 'refs/heads/main' }} # condition for only running this if HEAD is on main
        run: echo "Execute this step conditionally, only on main branch"

      - name: Send some output to logfile
        run: |
          echo "Hello ${{ matrix.browser }} ${{ matrix.device }}" > app_${{matrix.browser}}_${{matrix.device}}.log
          echo "This is another line" >> app_${{matrix.browser}}_${{matrix.device}}.log
          echo "Some error occurred!" > err_${{matrix.browser}}_${{matrix.device}}.log

      - name: Export results
        uses: actions/upload-artifact@v3 # this can be found in the github action marketplace -- ? https://github.com/actions/upload-artifact
        with:
          name: logs
          path: |
            app_${{matrix.browser}}_${{matrix.device}}.log
            err_${{matrix.browser}}_${{matrix.device}}.log


